apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: supriyaacr123.azurecr.io/react-node-ks-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /metrics
              port: 5000
          livenessProbe:
            httpGet:
              path: /metrics
              port: 5000  
      imagePullSecrets:
        - name: acr-secret1      
